import type { Metadata } from "next";
import { IRANSansX } from "./fonts";
import { SidebarProvider } from "@/components/ui/sidebar";
import { Toaster as Sonner } from "sonner";

import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${IRANSansX.className}`}>
        <SidebarProvider>
          <>
            {children}
            <Sonner
              richColors
              className={`${IRANSansX.className}`}
              closeButton
            />
          </>
        </SidebarProvider>
      </body>
    </html>
  );
}
